[build]
command = "bundle install && bundle exec jekyll build"
publish = "_site/"

[context.production.environment]
JEKYLL_ENV = "production"

[context.deploy-preview.environment]
JEKYLL_ENV = "development"
